[workspace]
members = [
  "crates/bloom-signer-backend-api",
  "crates/bloom-signer-backend-local",
  "crates/bloom-signer-backend-aws-kms",
  "crates/bloom-signer",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[workspace.dependencies]
bloom-triad-protocol = { path = "../bloom/crates/bloom-triad-protocol" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
zeroize = { version = "1", features = ["zeroize_derive"] }
futures = "0.3"
