[package]
name = "bloom-signer-backend-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bloom-signer-backend-api = { path = "../bloom-signer-backend-api" }
bip32.workspace = true
bloom-signer-api.workspace = true
bloom-signer-derive.workspace = true
chacha20poly1305.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
k256.workspace = true
parking_lot.workspace = true
rand.workspace = true
serde.workspace = true
serde_jcs.workspace = true
serde_json.workspace = true
sha2.workspace = true
sha3.workspace = true
zeroize.workspace = true

[dev-dependencies]
futures.workspace = true
serde_json.workspace = true
